-- USE [RbT24ODPRD4]
-- USE DB4 

--EXECUTE
-- 刪除舊檔案
DELETE [dbo].[RPT_DEFINE_EXE_ORDER] WHERE RPT_ID IN ('ALM10004', 'RPT_8D012') 
DELETE [dbo].[RPT_DEFINE_MASTER] WHERE RPT_ID IN ('ALM10004', 'RPT_8D012') 
DELETE [dbo].[RPT_DEFINE_OUTPUT]  WHERE RPT_ID IN ('ALM10004', 'RPT_8D012') 
DELETE [dbo].[RPT_DEFINE_BUSINESS_TYPE]  WHERE RPT_ID IN ('ALM10004', 'RPT_8D012')  

--RPT_DEFINE_EXE_ORDER新增
INSERT [dbo].[RPT_DEFINE_EXE_ORDER] ([RPT_ID], [STAGE], [EXE_ORDER], [SUB_ORDER]) VALUES (N'ALM10004', N'REPORT', 30, 9998)
INSERT [dbo].[RPT_DEFINE_EXE_ORDER] ([RPT_ID], [STAGE], [EXE_ORDER], [SUB_ORDER]) VALUES (N'RPT_8D012', N'REPORT', 40, 20)


--RPT_DEFINE_MASTER新增
INSERT [dbo].[RPT_DEFINE_MASTER] 
(
	[RPT_ID],[RPT_NAME],[RPT_TYPE],[BRANCH],[RPT_ALLOWED_PRINT]
    ,[RPT_ALLOWED_DOWNLOAD],[RPT_WATERMARK],[RPT_EXPIRY_MONTHS],[RPT_USER_LEVEL],[RPT_CYCLE]
	,[NON_USE_FLAG],[IS_JR],[LM_TIME],[CR_TIME],[TEMPLATE_VER]
	,[BATCH_GROUP]
) 
VALUES 
(
	N'ALM10004' --RPT_ID
	, N'ALM 定存明細檔 - 固定利率 ' --RPT_NAME
	, N'File' --RPT_TYPE(報表OR檔案)
	, N'HQ' --BRANCH(是否BY分行出表)
	, N'Y' --RPT_ALLOWED_PRINT(是否能列印)
	, N'Y' --RPT_ALLOWED_DOWNLOAD(是否能下載)
	, N'Y' --RPT_WATERMARK(浮水印)
	, 1 --RPT_EXPIRY_MONTHS(檔案保留多久)
	, CAST(30 AS Numeric(2, 0)) --RPT_USER_LEVEL
	, N'D' --RPT_CYCLE(日月年報)
	, N'Y' --NON_USE_FLAG(是否產檔)
	, N'N' --IS_JR (是否能看線上報表)
	, NULL --LM_TIME
	, NULL --CR_TIME
	, NULL --TEMPLATE_VER
	, N'ROD' --BATCH_GROUP
)

INSERT [dbo].[RPT_DEFINE_MASTER] 
(
	[RPT_ID],[RPT_NAME],[RPT_TYPE],[BRANCH],[RPT_ALLOWED_PRINT]
    ,[RPT_ALLOWED_DOWNLOAD],[RPT_WATERMARK],[RPT_EXPIRY_MONTHS],[RPT_USER_LEVEL],[RPT_CYCLE]
	,[NON_USE_FLAG],[IS_JR],[LM_TIME],[CR_TIME],[TEMPLATE_VER]
	,[BATCH_GROUP]
) 
VALUES 
(
	N'RPT_8D012' --RPT_ID
	, N'懸帳交易明細日報表 ' --RPT_NAME
	, N'Report' --RPT_TYPE(報表OR檔案)
	, N'HQ' --BRANCH(是否BY分行出表)
	, N'Y' --RPT_ALLOWED_PRINT(是否能列印)
	, N'Y' --RPT_ALLOWED_DOWNLOAD(是否能下載)
	, N'Y' --RPT_WATERMARK(浮水印)
	, 24 --RPT_EXPIRY_MONTHS(檔案保留多久)
	, CAST(30 AS Numeric(2, 0)) --RPT_USER_LEVEL
	, N'D' --RPT_CYCLE(日月年報)
	, N'N' --NON_USE_FLAG(是否產檔)
	, N'Y' --IS_JR (是否能看線上報表)
	, NULL --LM_TIME
	, NULL --CR_TIME
	, NULL --TEMPLATE_VER
	, N'ROD' --BATCH_GROUP
)

-- SIT 及 PROD產檔環境 
INSERT [dbo].[RPT_DEFINE_OUTPUT] 
(
	[RPT_ID],[OUTPUT_PATH],[FNAME_PATTERN],[FNAME_PATTERN_FLG],[FLG_TYPE]
    ,[CHARSET],[LINE_SEPARATOR],[DATA_LINE_DECORATE],[DATA_FIELD_DECORATE],[DATA_FIELD_DELIMITER]
    ,[PRINT_HEADER],[HEADER_LINE_DECORATE],[HEADER_FIELD_DECORATE],[HEADER_FIELD_DELIMITER],[PRINT_FOOTER]
	,[FOOTER_LINE_DECORATE],[FOOTER_FIELD_DECORATE],[FOOTER_FIELD_DELIMITER],[FILE_TYPE],[FLG_SEND]
	,[FILE_SEND]
)
VALUES 
(
	N'ALM10004' --RPT_ID(報表代號)
	, '/app/t24odap/filetxt/${rpt-date:yyyyMM}/${rpt-date:dd}/ALM' --OUTPUT_PATH(檔案儲存路徑)
	, 'FIX_T24_DEPOSIT_${rpt-date:yyyyMMdd}.CSV' --FNAME_PATTERN(資料檔檔名格式)
	, 'FIX_T24_DEPOSIT_${rpt-date:yyyyMMdd}.flg' --FNAME_PATTERN_FLG(檢核檔檔名格式)
	, 'RPT_FILE_NAME' --FLG_TYPE(檢核檔類別)
	, NULL --CHARSET(編碼)
	, NULL --LINE_SEPARATOR(換行符號)
	, NULL --DATA_LINE_DECORATE(資料列裝飾符號)
	, NULL --DATA_FIELD_DECORATE(資料欄位裝飾符號)
	, NULL --DATA_FIELD_DELIMITER(資料欄位分隔符號)
	, NULL --PRINT_HEADER(列印表頭)
	, NULL --HEADER_LINE_DECORATE(表頭裝飾符號)
	, NULL --HEADER_FIELD_DECORATE(表頭欄位裝飾符號)
	, NULL --HEADER_FIELD_DELIMITER(表頭欄位分隔符號)
	, NULL --PRINT_FOOTER(列印表尾)
	, NULL --FOOTER_LINE_DECORATE(表尾裝飾符號)
	, NULL --FOOTER_FIELD_DECORATE(表尾欄位裝飾符號	)
	, NULL --FOOTER_FIELD_DELIMITER(表尾欄位分隔符號)
	, NULL --FILE_TYPE(檔案類型)
	, NULL --FLG_SEND
	, NULL --FILE_SEND(檢核檔寄送)
) 

-- SIT 及 PROD產檔環境 
INSERT [dbo].[RPT_DEFINE_OUTPUT] 
(
	[RPT_ID],[OUTPUT_PATH],[FNAME_PATTERN],[FNAME_PATTERN_FLG],[FLG_TYPE]
    ,[CHARSET],[LINE_SEPARATOR],[DATA_LINE_DECORATE],[DATA_FIELD_DECORATE],[DATA_FIELD_DELIMITER]
    ,[PRINT_HEADER],[HEADER_LINE_DECORATE],[HEADER_FIELD_DECORATE],[HEADER_FIELD_DELIMITER],[PRINT_FOOTER]
	,[FOOTER_LINE_DECORATE],[FOOTER_FIELD_DECORATE],[FOOTER_FIELD_DELIMITER],[FILE_TYPE],[FLG_SEND]
	,[FILE_SEND]
)
VALUES 
(
	N'RPT_8D012' --RPT_ID(報表代號)
	, NULL --OUTPUT_PATH(檔案儲存路徑)
	, NULL --FNAME_PATTERN(資料檔檔名格式)
	, 'RPT_8D012.FLG' --FNAME_PATTERN_FLG(檢核檔檔名格式)
	, 'RPT_FILE_NAME' --FLG_TYPE(檢核檔類別)
	, NULL --CHARSET(編碼)
	, NULL --LINE_SEPARATOR(換行符號)
	, NULL --DATA_LINE_DECORATE(資料列裝飾符號)
	, NULL --DATA_FIELD_DECORATE(資料欄位裝飾符號)
	, NULL --DATA_FIELD_DELIMITER(資料欄位分隔符號)
	, NULL --PRINT_HEADER(列印表頭)
	, NULL --HEADER_LINE_DECORATE(表頭裝飾符號)
	, NULL --HEADER_FIELD_DECORATE(表頭欄位裝飾符號)
	, NULL --HEADER_FIELD_DELIMITER(表頭欄位分隔符號)
	, NULL --PRINT_FOOTER(列印表尾)
	, NULL --FOOTER_LINE_DECORATE(表尾裝飾符號)
	, NULL --FOOTER_FIELD_DECORATE(表尾欄位裝飾符號	)
	, NULL --FOOTER_FIELD_DELIMITER(表尾欄位分隔符號)
	, NULL --FILE_TYPE(檔案類型)
	, NULL --FLG_SEND
	, NULL --FILE_SEND(檢核檔寄送)
) 


-- 設定報表所屬的業務別  
INSERT [dbo].[RPT_DEFINE_BUSINESS_TYPE] ([RPT_ID], [RPT_BUSINESS_TYPE])  
VALUES ('RPT_8D012', 'GL01')  

-- BEFORE 
SELECT * FROM [dbo].[RPT_DEFINE_EXE_ORDER] WHERE RPT_ID IN ('ALM10004', 'RPT_8D012') 
SELECT * FROM [dbo].[RPT_DEFINE_MASTER] WHERE RPT_ID IN ('ALM10004', 'RPT_8D012') 
SELECT * FROM [dbo].[RPT_DEFINE_OUTPUT] WHERE RPT_ID IN ('ALM10004', 'RPT_8D012')  
SELECT * FROM [dbo].[RPT_DEFINE_BUSINESS_TYPE] WHERE RPT_ID IN ('ALM10004', 'RPT_8D012') 

-- 新增業務別 
--SELECT * FROM [dbo].[BUSINESS_TYPE_MASTER] WHERE [BUSINESS_TYPE] = 'GL01'
--SELECT * FROM [dbo].[BUSINESS_TYPE_DETAIL] WHERE [BUSINESS_TYPE] = 'GL01'  

 